name: PR-Sense
on:  pull_request_target

permissions:
  contents: read
  pull-requests: write
  issues: write          # für Kommentare in PRs

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./                       # ← deine Action
        with:
          openai_key: ${{ secrets.OPENAI_API_KEY }}
        env:                           #  ← HIER NEU!
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}   # war meist schon da
          ORG_GIST_ID:    ${{ secrets.ORG_GIST_ID }}
          ORG_GIST_TOKEN: ${{ secrets.ORG_GIST_TOKEN }}
